### ISSUE TITLE
Compile error: Invalid outside procedure

### ISSUE THREAD

**Issue by fireextinguisher** [TotallyInformation/outlook-filer#1]
Hi, I followed instructions, but received Compile error: Invalid outside procedure.

Following lines are highlighted with red font in code editor:
...
Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} FolderSelectBox
...
   OleObjectBlob = "FolderSelectBox.frx":0000
...

Denis.

**Comment by TotallyInformation** [comment]
What version of Outlook are you using? Also is it 32bit or 64bit?
Thanks.

**Comment by fireextinguisher** [comment]
Hi,

thank you for reply. I use Outlook 2013 32bit. I've actually managed to start macros. Problem was with frm file. It was loading into deparate module and form itself was not imported. So I've removed all source code from the  frm file and imported the form. After that I manually copied source code into form  object.

Denis.

**Comment by TotallyInformation** [comment]
Thanks for letting me know. It really needs some work but I've not any spare time at the moment.

**Comment by TotallyInformation** [comment]
Other issues open with same error.
