### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fireextinguisher** [TotallyInformation/outlook-filer#2]
Is it possible to index not only inbox subfolders, but folders from all opened PST files as well?

**Comment by TotallyInformation** [comment]
While not necessarily impossible, it is certainly complex. Too complex for me to get my head around with the time I have available at the moment I'm afraid.

However, I'd be happy to accept a pull request if you work out how to do it.

**Comment by TotallyInformation** [comment]
Closing since nobody has been able to offer further help.
