### ISSUE TITLE
Importing as new module instead of form

### ISSUE THREAD

**Issue by nicoleahmed** [TotallyInformation/outlook-filer#4]
Hi
I'd love to get this working.

Unlike other .frm files I've imported into outlook visual basic - this file gets imported into the modules section rather than the forms section.

![image](https://github.com/TotallyInformation/outlook-filer/assets/38244338/8713659c-dab6-4dad-954e-01dc2fe08116)

I'm going to see if I can manually create the form myself using the code and get it working - will let you know thanks.

**Comment by nicoleahmed** [comment]
I wonder Julian - if you are still using this in outlook, whether you could re-export from outlook vba for us? I wonder if the issue is because this was written and developed in office 2013

**Comment by TotallyInformation** [comment]
Hi, as mentioned in the other issue, no, I don't use it I'm afraid. My FileMe macro is great and I use it many times a day. It has the advantage that no form is needed. The disadvantage being that you really need to be working in a threaded inbox view for it to be of most value and, of course, you need at least 1 email in the thread to have already been filed.

**Comment by nicoleahmed** [comment]
Thanks Julian - that FileMe macro is great (I had missed it!) and solves the issue I had across different mailboxes too.  I will be using your macro a lot now. 

A similar macro here which may be of interest https://github.com/k4j8/outlook-move-to-thread 

re: your comment on the other issue - I think I will look at JavaScript too. Will let you know if I come up with anything.

All the best!
